development:
  adapter: postgresql
  database: ecommerce_development
  pool: 5
  timeout: 5000
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

test:
  adapter: postgresql
  database: ecommerce_test
  pool: 5
  timeout: 5000
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

production:
  adapter: postgresql
  database: ecommerce_production
  pool: 5
  timeout: 5000