development:
  POSTGRESQL_USERNAME: 'User'
  POSTGRESQL_PASSWORD: 'Pass'
  ECOMMERCE_REPLY_TO_EMAIL: 'hello@gmail.com'
  ECOMMERCE_CONTACT_EMAIL: 'hello@gmail.com'
  ECOMMERCE_FACEBOOK_KEY: ''
  ECOMMERCE_FACEBOOK_SECRET: ''
  ECOMMERCE_GMAIL_USERNAME: 'hello@gmail.com'
  ECOMMERCE_GMAIL_PASSWORD: 'myPassword123'
  ECOMMERCE_GOOGLE_ANALYTICS_CODE: 'UA-xxxxxxxx-x'
  S3_BUCKET_NAME: 's3_bucket_name'
  AWS_ACCESS_KEY_ID: 'aws_access_key_id'
  AWS_SECRET_ACCESS_KEY: 'aws_secret_access_key'
  AWS_REGION: 'aws_region'
  STRIPE_API_KEY: 'sk_test_xxxxxx'
test:
  POSTGRESQL_USERNAME: 'User'
  POSTGRESQL_PASSWORD: 'Pass'
production:
  ECOMMERCE_REPLY_TO_EMAIL: 'hello@gmail.com'
  ECOMMERCE_CONTACT_EMAIL: 'hello@gmail.com'
  ECOMMERCE_FACEBOOK_KEY: ''
  ECOMMERCE_FACEBOOK_SECRET: ''
  ECOMMERCE_GMAIL_USERNAME: 'hello@gmail.com'
  ECOMMERCE_GMAIL_PASSWORD: 'myPassword123'
  ECOMMERCE_GOOGLE_ANALYTICS_CODE: 'UA-xxxxxxxx-x'
  S3_BUCKET_NAME: 's3_bucket_name'
  AWS_ACCESS_KEY_ID: 'aws_access_key_id'
  AWS_SECRET_ACCESS_KEY: 'aws_secret_access_key'
  AWS_REGION: 'aws_region'
  STRIPE_API_KEY: 'sk_test_xxxxxx'